### ISSUE TITLE
Morph Shapes Bug

### ISSUE THREAD

**Issue by adrianoresende** [mattrothenberg/vue-overdrive#7] opened 2018-04-03 23:43 UTC
Very cool this effect overdrive. 👏 

I found a problem, if change the pages more fast, can happen a bug easily.
I believe this behavior of to change pages more fast is common.

**Comment by mattrothenberg** [comment] 2018-04-03 23:56
Can you please include a link so I can reproduce this issue on my end?

Thanks!

**Comment by adrianoresende** [comment] 2018-04-03 23:58
I tested in first example
https://vue-overdrive.netlify.com/#/shapes

**Comment by mattrothenberg** [comment] 2018-04-04 00:04
I'm not observing this on my end. Closing for the time being, as this doesn't seem like a "common" issue for others (haven't seen any other issues opened to this end)

**Closed by mattrothenberg** 2018-04-04 00:04 UTC

**Comment by matthiasg** [comment] 2018-04-04 08:44
Just clicking through the shapes on my end, at first slowly then alternating very quickly between two states I also very quickly get into a buggy state

![morph-bug](https://user-images.githubusercontent.com/231889/38297551-1d18a5c2-37f5-11e8-9844-31251fc33e0d.gif)

**Comment by mattrothenberg** [comment] 2018-04-04 10:36
@matthiasg @adrianoresende Is this more to your liking? I realized the Netlify link was using a very old version of the library, so I updated it and I _think_ the bug has gone away.

![kapture 2018-04-04 at 6 35 34](https://user-images.githubusercontent.com/5148596/38302940-78f306f8-37d2-11e8-9856-820efa1cf4c1.gif)

**Comment by matthiasg** [comment] 2018-04-04 11:53
@mattrothenberg did not expect you to fix this right away :) Seems indeed gone, could not reproduce anymore, before it took just a few attempts. 👍

**Comment by matthiasg** [comment] 2018-04-04 11:57
@mattrothenberg btw .. as for the bug. in my experience sometimes users to click quickly (especially power users) and it is also an indication that state management is not stable and could fail at any time and is difficult to diagnose then. It definitely doesn't inspire confidence and especially power users would get an impression of fancy graphics gone wrong :)

but in this specific case I just saw @adrianoresende's comment and wanted to second it in so far as I could also reproduce his issue

**Comment by mattrothenberg** [comment] 2018-04-04 13:15
Thanks guys, the feedback is much appreciated. Sorry for not understanding the original issue
